global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: amardeep.gupta@atcs.com
    from: donotreply@emea.com
    smarthost: mailhost.emea.svc.corpintra.net:25
    auth_username: NA
    auth_identity: NA
    auth_password: NA
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
