global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
# Rules and alerts are read from the specified file(s)
rule_files:
  - /etc/prometheus/server/prometheus/rules.yml
  
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - 172.17.0.3:9093
        
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [172.17.0.2:9090]  
- job_name: gdadmin
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets: [172.17.0.5:4012]
